language: php

dist: xenial

services:
    - docker
addons:
    sonarcloud:
        organization: "morgonus"
matrix:
    include:
        - php: 7.4
          env: deps=high
        - php: 8.0
          env: deps=low
    fast_finish: true

before_install:
    - composer install
script:
    - echo "test"
